config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", :as => :rails_health_check

  resources :estates, shallow: true, only: [:index, :show, :create, :update, :destroy] do
    resources :people, only: [:index, :create, :update]
    # In estate planning, I assume version control is essential - no ability to destroy docs
    resources :documents, only: [:index, :create, :update]
  end

  resources :advisors, shallow: true, only: [:index, :create, :show] do
    resources :estates, only: [:index, :update]
  end

end

app/models/advisor.rb
class Advisor < ApplicationRecord
  has_many :estates

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :estate
end

app/models/estate.rb
class Estate < ApplicationRecord
  has_many :people
  has_many :documents

  # validates :people, presence: true
  # validates :must_have_one_grantor

  private

  # def must_have_one_grantor
  # # must have 1 grantor
  # end

end

app/models/person.rb
class Person < ApplicationRecord
  enum role: [:grantor, :beneficiary, :executor, :conservator, :power_of_attorney, :fiduciary, :trustee]

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  def index
    @advisors = Advisor.all
  end

  def create
    Advisor.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.all
  end

  def create
    Document.new
  end
end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  def index
    @estates = Estate.all
  end

  def new
    @estates = Estate.new
  end

  def create
    @estates = Estate.new(owner_first_name: "...", owner_last_name: "...", state: 'MA')
  end

  def show
    @estates = Estate.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def create
    Person.new
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/estates_helper.rb
module EstatesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/advisors/index.html.erb
<h1>Advisors#index</h1>
<p>Find me in app/views/advisors/index.html.erb</p>

app/views/document/index.html.erb
<h1>Document#index</h1>
<p>Find me in app/views/document/index.html.erb</p>

app/views/estates/_form.html.erb
<%= form_with(model: estate) do |form| %>
  <% if estate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estate.errors.count, "error") %> prohibited this estate from being saved:</h2>

      <ul>
        <% estate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title, "Title:" %>
  <%= form.text_field :title %>

  <%= form.label :text, "Text:" %>
  <%= form.text_area :text %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estates</h1>

<table>
  <thead>
     <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estates.each do |estate| %>
      <tr>
        <td><%= estate.owner_first_name %></td>
        <td><%= link_to 'Show', estate %></td>
        <td><%= link_to 'Edit', edit_estate_path(estate) %></td>
        <td><%= link_to 'Destroy', estate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
   </tbody>
</table>

<br>

app/views/estates/new.html.erb
<%= form_for :estate, url: estates_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VanillaBean</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1>People#index</h1>
<p>Find me in app/views/people/index.html.erb</p>